### PR TITLE
Signing the assembly so it can be deployed to gac

### PR DESCRIPTION
**Pull request by baywet**
For SharePoint full trust solutions we need the assemblies to be signed.
It's a good practice in general to sign assemblies to consumer applications can "authenticate" the assembly somehow.
As it does not seem this project has a PKI I just used a self signed certificate.

### CODE REVIEW

**Comment by PureKrome** [comment]
Hi @baywet and thanks so much for the PR!! really really appreciate it :)

Ok, so this PR makes the dll *signed* ?

**Comment by baywet** [comment]
Hi @purekrome no problem. Yes that's what it does. Doing so the DLL can now be deployed to the gac and all other stuff requiring a strong assembly name can be done.

**Comment by PureKrome** [comment]
Hi @baywet - thanks heaps for the prompt reply. Again, really appreciate it.

I'm going to have to decline this PR because I take a strong stance *against* strong name signing.

To understand my reasons, please refer to https://github.com/octokit/octokit.rb/issues/405 - this is an almighty magical thread about the pro's and con's to it. An epic battle of debate.

In short, the solution to people who require SNS is to clone the repo, sign it yourself and use that.

Yes, I can merge.
Yes, I can have 2x nugets, etc.
No, I don't want to support this and therefore I take a strong stand, *against* it.

Honest and sincere regards,

-PK-

**Comment by baywet** [comment]
Hi @PureKrome 
Thanks for considering the PR and taking the time to answer me.
Went over and read parts of this epic debate, very interesting debate. I don't want to reenact it here so I won't be debating. The reason why I wanted to add SN signing to this project was mostly to support GAC deployment (which is the way to go most of the time when you're doing SharePoint development).
Even if I don't necessarily agree with you, I understand your point and I won't be pushing this PR any further.
We'll find solutions on our end like app_bin deployment and/or signing it in our CI.
Regards
Vincent

**Pull request closed without merging**
